package com.snail.pojo.domain;

import java.util.Date;

public class UserLoginLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.login_log_id
     *
     * @mbggenerated
     */
    private Integer loginLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.login_id
     *
     * @mbggenerated
     */
    private Integer loginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.login_time
     *
     * @mbggenerated
     */
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.login_ip
     *
     * @mbggenerated
     */
    private String loginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.login_type
     *
     * @mbggenerated
     */
    private String loginType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.login_result
     *
     * @mbggenerated
     */
    private String loginResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.token
     *
     * @mbggenerated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.user_mobile
     *
     * @mbggenerated
     */
    private String userMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.user_email
     *
     * @mbggenerated
     */
    private String userEmail;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_log
     *
     * @mbggenerated
     */
    public UserLoginLog(Integer loginLogId, Integer loginId, Date loginTime, String loginIp, String loginType, String loginResult, String token, String userMobile, String userEmail) {
        this.loginLogId = loginLogId;
        this.loginId = loginId;
        this.loginTime = loginTime;
        this.loginIp = loginIp;
        this.loginType = loginType;
        this.loginResult = loginResult;
        this.token = token;
        this.userMobile = userMobile;
        this.userEmail = userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_log
     *
     * @mbggenerated
     */
    public UserLoginLog() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.login_log_id
     *
     * @return the value of user_login_log.login_log_id
     *
     * @mbggenerated
     */
    public Integer getLoginLogId() {
        return loginLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.login_log_id
     *
     * @param loginLogId the value for user_login_log.login_log_id
     *
     * @mbggenerated
     */
    public void setLoginLogId(Integer loginLogId) {
        this.loginLogId = loginLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.login_id
     *
     * @return the value of user_login_log.login_id
     *
     * @mbggenerated
     */
    public Integer getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.login_id
     *
     * @param loginId the value for user_login_log.login_id
     *
     * @mbggenerated
     */
    public void setLoginId(Integer loginId) {
        this.loginId = loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.login_time
     *
     * @return the value of user_login_log.login_time
     *
     * @mbggenerated
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.login_time
     *
     * @param loginTime the value for user_login_log.login_time
     *
     * @mbggenerated
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.login_ip
     *
     * @return the value of user_login_log.login_ip
     *
     * @mbggenerated
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.login_ip
     *
     * @param loginIp the value for user_login_log.login_ip
     *
     * @mbggenerated
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp == null ? null : loginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.login_type
     *
     * @return the value of user_login_log.login_type
     *
     * @mbggenerated
     */
    public String getLoginType() {
        return loginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.login_type
     *
     * @param loginType the value for user_login_log.login_type
     *
     * @mbggenerated
     */
    public void setLoginType(String loginType) {
        this.loginType = loginType == null ? null : loginType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.login_result
     *
     * @return the value of user_login_log.login_result
     *
     * @mbggenerated
     */
    public String getLoginResult() {
        return loginResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.login_result
     *
     * @param loginResult the value for user_login_log.login_result
     *
     * @mbggenerated
     */
    public void setLoginResult(String loginResult) {
        this.loginResult = loginResult == null ? null : loginResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.token
     *
     * @return the value of user_login_log.token
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.token
     *
     * @param token the value for user_login_log.token
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.user_mobile
     *
     * @return the value of user_login_log.user_mobile
     *
     * @mbggenerated
     */
    public String getUserMobile() {
        return userMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.user_mobile
     *
     * @param userMobile the value for user_login_log.user_mobile
     *
     * @mbggenerated
     */
    public void setUserMobile(String userMobile) {
        this.userMobile = userMobile == null ? null : userMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.user_email
     *
     * @return the value of user_login_log.user_email
     *
     * @mbggenerated
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.user_email
     *
     * @param userEmail the value for user_login_log.user_email
     *
     * @mbggenerated
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }
}