package com.snail.pojo.domain;

import java.math.BigDecimal;
import java.util.Date;

public class UserAccountLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_log.account_log_id
     *
     * @mbggenerated
     */
    private Integer accountLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_log.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_log.source
     *
     * @mbggenerated
     */
    private Integer source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_log.trans_serial
     *
     * @mbggenerated
     */
    private String transSerial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_log.amount
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_log.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_log.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_log
     *
     * @mbggenerated
     */
    public UserAccountLog(Integer accountLogId, Integer userId, Integer source, String transSerial, BigDecimal amount, Date createTime, Date updateTime) {
        this.accountLogId = accountLogId;
        this.userId = userId;
        this.source = source;
        this.transSerial = transSerial;
        this.amount = amount;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_log
     *
     * @mbggenerated
     */
    public UserAccountLog() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_log.account_log_id
     *
     * @return the value of user_account_log.account_log_id
     *
     * @mbggenerated
     */
    public Integer getAccountLogId() {
        return accountLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_log.account_log_id
     *
     * @param accountLogId the value for user_account_log.account_log_id
     *
     * @mbggenerated
     */
    public void setAccountLogId(Integer accountLogId) {
        this.accountLogId = accountLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_log.user_id
     *
     * @return the value of user_account_log.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_log.user_id
     *
     * @param userId the value for user_account_log.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_log.source
     *
     * @return the value of user_account_log.source
     *
     * @mbggenerated
     */
    public Integer getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_log.source
     *
     * @param source the value for user_account_log.source
     *
     * @mbggenerated
     */
    public void setSource(Integer source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_log.trans_serial
     *
     * @return the value of user_account_log.trans_serial
     *
     * @mbggenerated
     */
    public String getTransSerial() {
        return transSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_log.trans_serial
     *
     * @param transSerial the value for user_account_log.trans_serial
     *
     * @mbggenerated
     */
    public void setTransSerial(String transSerial) {
        this.transSerial = transSerial == null ? null : transSerial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_log.amount
     *
     * @return the value of user_account_log.amount
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_log.amount
     *
     * @param amount the value for user_account_log.amount
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_log.create_time
     *
     * @return the value of user_account_log.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_log.create_time
     *
     * @param createTime the value for user_account_log.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_log.update_time
     *
     * @return the value of user_account_log.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_log.update_time
     *
     * @param updateTime the value for user_account_log.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}