package com.snail.dao;

import com.snail.pojo.domain.UserPic;
import com.snail.pojo.domain.UserPicExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface UserPicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pic
     *
     * @mbggenerated
     */
    int countByExample(UserPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pic
     *
     * @mbggenerated
     */
    int deleteByExample(UserPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pic
     *
     * @mbggenerated
     */
    @Delete({
        "delete from `user_pic`",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pic
     *
     * @mbggenerated
     */
    @Insert({
        "insert into `user_pic` (`id`, `url`, ",
        "`hash_code`, `user_id`, ",
        "`create_at`, `update_at`)",
        "values (#{id,jdbcType=INTEGER}, #{url,jdbcType=VARCHAR}, ",
        "#{hashCode,jdbcType=VARCHAR}, #{userId,jdbcType=INTEGER}, ",
        "#{createAt,jdbcType=TIMESTAMP}, #{updateAt,jdbcType=TIMESTAMP})"
    })
    int insert(UserPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pic
     *
     * @mbggenerated
     */
    int insertSelective(UserPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pic
     *
     * @mbggenerated
     */
    List<UserPic> selectByExample(UserPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pic
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "`id`, `url`, `hash_code`, `user_id`, `create_at`, `update_at`",
        "from `user_pic`",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    UserPic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pic
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserPic record, @Param("example") UserPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pic
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserPic record, @Param("example") UserPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pic
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pic
     *
     * @mbggenerated
     */
    @Update({
        "update `user_pic`",
        "set `url` = #{url,jdbcType=VARCHAR},",
          "`hash_code` = #{hashCode,jdbcType=VARCHAR},",
          "`user_id` = #{userId,jdbcType=INTEGER},",
          "`create_at` = #{createAt,jdbcType=TIMESTAMP},",
          "`update_at` = #{updateAt,jdbcType=TIMESTAMP}",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UserPic record);
}